---
- name: configure sharding role incorrectly

  hosts: all

  roles:

    - nephelaiio.plugins

  tasks:

    - name: set base facts
      ansible.builtin.set_fact:
        _sharding_failed: false

    - name: attempt broken replicaset sharding configuration
      block:

        - name: deploy mongodb
          ansible.builtin.include_role:
            name: wpnops.mongodb
          vars:
            mongodb_sharding_role: error
            mongodb_addresses: "{{ play_hosts | map('extract', hostvars, ['ansible_default_ipv4', 'address']) }}"
            mongodb_members: "{{ mongodb_addresses | list }}"
            mongodb_replicaset_members: "{{ mongodb_members | map('map_format', '%s:' + mongodb_port) | list }}"

      rescue:

        - name: set result facts
          ansible.builtin.set_fact:
            _sharding_failed: true

    - name: fail on rename success
      ansible.builtin.fail:
        msg: "sharding role configuration operation must fail"
      when: not _rename_failed


- name: include commong converge play
  include_play: ../common/converge.yml
