---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: mongodb1
    image: "geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_COMMAND:-"/lib/systemd/systemd"}
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    tmpfs:
      - /tmp
      - /opt
  - name: mongodb2
    image: "geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_COMMAND:-"/lib/systemd/systemd"}
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    tmpfs:
      - /tmp
      - /opt
  - name: mongodb3
    image: "geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_COMMAND:-"/lib/systemd/systemd"}
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    tmpfs:
      - /tmp
      - /opt
provisioner:
  name: ansible
  playbooks:
    prepare: ../common/prepare.yml
    converge: ../common/converge.yml
    verify: ../common/verify.yml
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
  inventory:
    hosts:
      all:
        vars:
          mongodb_replicaset_name: test
          mongodb_firewall_state: stopped
          mongodb_sharding_role: shardsvr
verifier:
  name: ansible
scenario:
  prepare_sequence:
    - prepare
  converge_sequence:
    - converge
  destroy_sequence:
    - destroy
  cleanup_sequence:
    - cleanup
