---
- name: Manage MongoDB services
  block:

    - name: Manage MongoDB service
      ansible.builtin.service:
        name: "{{ mongodb_service_name }}"
        state: "{{ mongodb_service_state }}"
        enabled: true

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Wait for MongoDB to be up
      community.mongodb.mongodb_shell:
        eval: "db.runCommand({ping: 1})"
        mongo_cmd: "{{ mongodb_shell | default(omit) }}"
      changed_when: false
      retries: 6
      delay: 10
      when: mongodb_service_state != "stopped"
