---
- name: Deploy MongoDB
  hosts: all
  tasks:
    - name: Deploy mongodb
      ansible.builtin.include_role:
        name: wpnops.mongodb
      vars:
        mongodb_addresses: "{{ play_hosts | map('extract', hostvars, ['ansible_default_ipv4', 'address']) }}"
        mongodb_members: "{{ mongodb_addresses | list }}"
        mongodb_replicaset_members: "{{ mongodb_members | map('nephelaiio.plugins.map_format', '%s:' + mongodb_port) | list }}"
