---
- name: Destroy

  hosts: localhost

  connection: local

  tasks:

    - name: Destroy molecule instance(s)
      community.general.docker_container:
        name: "{{ item.name }}"
        state: absent
        force_kill: "{{ item.force_kill | default(True) }}"
      loop: "{{ molecule_yml.platforms }}"
