---
- name: Verify mongodb
  hosts: all
  become: true
  vars:
    mongodb_test:
      name: "Test"
  tasks:
    - name: Retrieve MongoDB replicaset status
      community.mongodb.mongodb_status:
        replica_set: "{{ mongodb_replicaset_name }}"
        validate: minimal
        poll: 5
        interval: 10
      register: mongodb_rs
      run_once: true

    - name: Determine MongoDB replicaset primary
      ansible.builtin.set_fact:
        replicaset_primary: "{{ ansible_fqdn if _replicaset_primary == ansible_default_ipv4.address }}"
      vars:
        _mongodb_replicaset: "{{ mongodb_rs.replicaset | dict2items }}"
        _replicaset_primary_dict: "{{ _mongodb_replicaset | selectattr('value', 'equalto', 'PRIMARY') }}"
        _replicaset_primary_list: "{{ _replicaset_primary_dict | map(attribute='key') | map('nephelaiio.plugins.split_with', ':') | map('first') }}"
        _replicaset_primary: "{{ _replicaset_primary_list | flatten | first }}"

    - name: Evaluate MongoDB shell commands
      when: replicaset_primary
      block:
        - name: Create MongoDB test database
          community.mongodb.mongodb_shell:
            login_database: "testdb"
            eval: "db.test.insert({{ mongodb_test }})"
          register: mongodb_shell_output

        - name: List MongoDB databases
          community.mongodb.mongodb_shell:
            eval: "db.adminCommand('listDatabases')"
            stringify: true
          changed_when: false
          register: mongodb_shell_output

        - name: Find MongoDB test database metadata
          community.mongodb.mongodb_shell:
            login_database: "testdb"
            eval: "db.test.find({{ mongodb_test }}).toArray()"
          failed_when: mongodb_shell_output.transformed_output | length == 0
          changed_when: false
          register: mongodb_shell_output

        - name: Drop MongoDB test database
          community.mongodb.mongodb_shell:
            login_database: "testdb"
            eval: "db.dropDatabase()"
          changed_when: false
