---
- name: Reconfigure MongoDB replica set
  community.mongodb.mongodb_replicaset:
    replica_set: "{{ mongodb_replicaset_name }}"
    members: "{{ _members_update }}"
    reconfigure: true
    validate: false
  delegate_to: "{{ replicaset_primary }}"

- name: Change MongoDB replicaset priority new members
  when: _add_member | default(false) | bool
  block:

    - name: Wait for replica set to stabilize
      community.mongodb.mongodb_status:
        replica_set: "{{ mongodb_replicaset_name }}"
        validate: minimal
        poll: "{{ mongodb_reconfig_poll }}"
        interval: "{{ mongodb_reconfig_interval }}"
      delegate_to: "{{ replicaset_primary }}"

    - name: Reconfigure MongoDB replica set
      community.mongodb.mongodb_replicaset:
        replica_set: "{{ mongodb_replicaset_name }}"
        members: "{{ _existing + [_update_member] }}"
        reconfigure: true
        validate: false
      vars:
        _update_member:
          host: "{{ _mongodb_member }}"
          hidden: false
          votes: 1
          priority: 1
      delegate_to: "{{ replicaset_primary }}"

    - name: Wait for replica set to stabilize
      community.mongodb.mongodb_status:
        replica_set: "{{ mongodb_replicaset_name }}"
        validate: minimal
        poll: "{{ mongodb_reconfig_poll }}"
        interval: "{{ mongodb_reconfig_interval }}"
      delegate_to: "{{ replicaset_primary }}"

- name: Gather MongoDB existing replica set members
  community.mongodb.mongodb_shell:
    eval: "rs.status().members"
  changed_when: false
  register: mongodb_status
  retries: 6
  delay: 10
  until: mongodb_status is success
  delegate_to: "{{ replicaset_primary }}"

- name: Compute MongoDB existing replica set members
  ansible.builtin.set_fact:
    _existing_members: "{{ _members_list | map(attribute='name') }}"
  vars:
    _members_list: "{{ mongodb_status.transformed_output | list }}"
