---
- name: Configure 3 replicaset nodes
  hosts: "{{ groups['all'][:3] | join(':') }}"
  tasks:
    - name: Destroy mongodb configuration
      ansible.builtin.file:
        dest: /etc/mongod.conf
        state: absent

    - name: Deploy mongodb
      ansible.builtin.include_role:
        name: wpnops.mongodb
      vars:
        _addresses: "{{ play_hosts | map('extract', hostvars, ['ansible_default_ipv4', 'address']) }}"
        _members: "{{ _addresses | list }}"
        mongodb_replicaset_members: "{{ _members | map('nephelaiio.plugins.map_format', '%s:' + mongodb_port) | list }}"
