---
- name: Configure 3 replicaset nodes
  hosts: "{{ groups['all'][:3] | join(':') }}"
  tasks:
    - name: Deploy mongodb
      ansible.builtin.include_role:
        name: wpnops.mongodb
      vars:
        _map_filter: "nephelaiio.plugins.map_format"
        mongodb_replicaset_members: "{{ play_hosts | map(_map_filter, '%s:' + mongodb_port) | list }}"
