---
- name: Configure 5 replicaset nodes
  hosts: "{{ groups['all'][:5] | join(':') }}"
  tasks:
    - name: Create virtualenv
      ansible.builtin.tempfile:
        state: directory
        prefix: .virtualenv
        path: "~"
      register: _virtualenv_tmpdir
      changed_when: false

    - name: Initialize virtualenv
      ansible.builtin.pip:
        name:
          - pip
        virtualenv: "{{ _virtualenv_tmpdir.path }}/venv"

    - name: Change python interpreter
      ansible.builtin.set_fact:
        ansible_python_interpreter: "{{ _virtualenv_tmpdir.path }}/venv/bin/python"

    - name: Deploy mongodb
      block:
        - name: Include mongodb role
          ansible.builtin.include_role:
            name: wpnops.mongodb
          vars:
            _map_format: 'nephelaiio.plugins.map_format'
            _addr_attrs: ['ansible_default_ipv4', 'address']
            _addresses: "{{ play_hosts | map('extract', hostvars, _addr_attrs) }}"
            _members: "{{ _addresses | list }}"
            mongodb_replicaset_members: "{{ _members | map(_map_format, '%s:' + mongodb_port) | list }}"

      always:
        - name: Destroy virtualenv
          ansible.builtin.file:
            path: "{{ _virtualenv_tmpdir.path }}"
            state: absent
          changed_when: false


- name: Include common converge play
  import_playbook: ../common/converge.yml


- name: Scale down to 5 replicaset nodes
  hosts: "{{ groups['all'][:5] | join(':') }}"
  tasks:
    - name: Create virtualenv
      ansible.builtin.tempfile:
        state: directory
        prefix: .virtualenv
        path: "~"
      register: _virtualenv_tmpdir
      changed_when: false

    - name: Initialize virtualenv
      ansible.builtin.pip:
        name:
          - pip
        virtualenv: "{{ _virtualenv_tmpdir.path }}/venv"

    - name: Change python interpreter
      ansible.builtin.set_fact:
        ansible_python_interpreter: "{{ _virtualenv_tmpdir.path }}/venv/bin/python"

    - name: Deploy mongodb
      block:
        - name: Include mongodb role
          ansible.builtin.include_role:
            name: wpnops.mongodb
          vars:
            _map_format: 'nephelaiio.plugins.map_format'
            _addr_attrs: ['ansible_default_ipv4', 'address']
            _addresses: "{{ play_hosts | map('extract', hostvars, _addr_attrs) }}"
            _members: "{{ _addresses | list }}"
            mongodb_replicaset_members: "{{ _members | map(_map_format, '%s:' + mongodb_port) | list }}"

      always:
        - name: Destroy virtualenv
          ansible.builtin.file:
            path: "{{ _virtualenv_tmpdir.path }}"
            state: absent
          changed_when: false


- name: Scale down to 3 replicaset nodes
  hosts: "{{ groups['all'][:3] | join(':') }}"
  tasks:
    - name: Create virtualenv
      ansible.builtin.tempfile:
        state: directory
        prefix: .virtualenv
        path: "~"
      register: _virtualenv_tmpdir
      changed_when: false

    - name: Initialize virtualenv
      ansible.builtin.pip:
        name:
          - pip
        virtualenv: "{{ _virtualenv_tmpdir.path }}/venv"

    - name: Change python interpreter
      ansible.builtin.set_fact:
        ansible_python_interpreter: "{{ _virtualenv_tmpdir.path }}/venv/bin/python"

    - name: Deploy mongodb
      block:
        - name: Include mongodb role
          ansible.builtin.include_role:
            name: wpnops.mongodb
          vars:
            _map_format: 'nephelaiio.plugins.map_format'
            _addr_attrs: ['ansible_default_ipv4', 'address']
            _addresses: "{{ play_hosts | map('extract', hostvars, _addr_attrs) }}"
            _members: "{{ _addresses | list }}"
            mongodb_replicaset_members: "{{ _members | map(_map_format, '%s:' + mongodb_port) | list }}"

      always:
        - name: Destroy virtualenv
          ansible.builtin.file:
            path: "{{ _virtualenv_tmpdir.path }}"
            state: absent
          changed_when: false


- name: Configure 1 replicaset node
  hosts: "{{ groups['all'][:1] | join(':') }}"
  tasks:
    - name: Set base facts
      ansible.builtin.set_fact:
        _members_failed: false

    - name: Create virtualenv
      ansible.builtin.tempfile:
        state: directory
        prefix: .virtualenv
        path: "~"
      register: _virtualenv_tmpdir
      changed_when: false

    - name: Initialize virtualenv
      ansible.builtin.pip:
        name:
          - pip
        virtualenv: "{{ _virtualenv_tmpdir.path }}/venv"

    - name: Change python interpreter
      ansible.builtin.set_fact:
        ansible_python_interpreter: "{{ _virtualenv_tmpdir.path }}/venv/bin/python"

    - name: Attempt broken replicaset sharding configuration
      block:
        - name: Deploy mongodb
          ansible.builtin.include_role:
            name: wpnops.mongodb
          vars:
            _map_format: 'nephelaiio.plugins.map_format'
            _addr_attrs: ['ansible_default_ipv4', 'address']
            _addresses: "{{ play_hosts | map('extract', hostvars, _addr_attrs) }}"
            _members: "{{ _addresses | list }}"
            mongodb_replicaset_members: "{{ _members | map(_map_format, '%s:' + mongodb_port) | list }}"

      rescue:
        - name: Set result facts
          ansible.builtin.set_fact:
            _members_failed: true

      always:
        - name: Destroy virtualenv
          ansible.builtin.file:
            path: "{{ _virtualenv_tmpdir.path }}"
            state: absent
          changed_when: false

    - name: Fail on broken replicaset member configuration
      ansible.builtin.fail:
        msg: "broken replicaset member configuration operation must fail"
      when: not _members_failed


- name: Configure 2 replicaset nodes
  hosts: "{{ groups['all'][:2] | join(':') }}"
  tasks:
    - name: Set base facts
      ansible.builtin.set_fact:
        _members_failed: false

    - name: Create virtualenv
      ansible.builtin.tempfile:
        state: directory
        prefix: .virtualenv
      register: _virtualenv_tmpdir
      changed_when: false

    - name: Initialize virtualenv
      ansible.builtin.pip:
        name:
          - pip
        virtualenv: "{{ _virtualenv_tmpdir.path }}/venv"

    - name: Change python interpreter
      ansible.builtin.set_fact:
        ansible_python_interpreter: "{{ _virtualenv_tmpdir.path }}/venv/bin/python"

    - name: Attempt broken replicaset sharding configuration
      block:
        - name: Deploy mongodb
          ansible.builtin.include_role:
            name: wpnops.mongodb
          vars:
            _map_format: 'nephelaiio.plugins.map_format'
            _addr_attrs: ['ansible_default_ipv4', 'address']
            _addresses: "{{ play_hosts | map('extract', hostvars, _addr_attrs) }}"
            _members: "{{ _addresses | list }}"
            mongodb_replicaset_members: "{{ _members | map(_map_format, '%s:' + mongodb_port) | list }}"

      rescue:
        - name: Set result facts
          ansible.builtin.set_fact:
            _members_failed: true

      always:
        - name: Destroy virtualenv
          ansible.builtin.file:
            path: "{{ _virtualenv_tmpdir.path }}"
            state: absent
          changed_when: false

    - name: Fail on broken replicaset member configuration
      ansible.builtin.fail:
        msg: "broken replicaset member configuration operation must fail"
      when: not _members_failed


- name: Configure 4 replicaset nodes
  hosts: "{{ groups['all'][:4] | join(':') }}"
  tasks:
    - name: Set base facts
      ansible.builtin.set_fact:
        _members_failed: false

    - name: Create virtualenv
      ansible.builtin.tempfile:
        state: directory
        prefix: .virtualenv
        path: "~"
      register: _virtualenv_tmpdir
      changed_when: false

    - name: Initialize virtualenv
      ansible.builtin.pip:
        name:
          - pip
        virtualenv: "{{ _virtualenv_tmpdir.path }}/venv"

    - name: Change python interpreter
      ansible.builtin.set_fact:
        ansible_python_interpreter: "{{ _virtualenv_tmpdir.path }}/venv/bin/python"

    - name: Attempt broken replicaset sharding configuration
      block:
        - name: Deploy mongodb
          ansible.builtin.include_role:
            name: wpnops.mongodb
          vars:
            _map_format: 'nephelaiio.plugins.map_format'
            _addr_attrs: ['ansible_default_ipv4', 'address']
            _addresses: "{{ play_hosts | map('extract', hostvars, _addr_attrs) }}"
            _members: "{{ _addresses | list }}"
            mongodb_replicaset_members: "{{ _members | map(_map_format, '%s:' + mongodb_port) | list }}"

      rescue:
        - name: Set result facts
          ansible.builtin.set_fact:
            _members_failed: true

      always:
        - name: Destroy virtualenv
          ansible.builtin.file:
            path: "{{ _virtualenv_tmpdir.path }}"
            state: absent
          changed_when: false

    - name: Fail on broken replicaset member configuration
      ansible.builtin.fail:
        msg: "broken replicaset member configuration operation must fail"
      when: not _members_failed


- name: Configure 6 replicaset nodes
  hosts: "{{ groups['all'][:6] | join(':') }}"
  tasks:
    - name: Set base facts
      ansible.builtin.set_fact:
        _members_failed: false

    - name: Create virtualenv
      ansible.builtin.tempfile:
        state: directory
        prefix: .virtualenv
        path: "~"
      register: _virtualenv_tmpdir
      changed_when: false

    - name: Initialize virtualenv
      ansible.builtin.pip:
        name:
          - pip
        virtualenv: "{{ _virtualenv_tmpdir.path }}/venv"

    - name: Change python interpreter
      ansible.builtin.set_fact:
        ansible_python_interpreter: "{{ _virtualenv_tmpdir.path }}/venv/bin/python"

    - name: Attempt broken replicaset sharding configuration
      block:
        - name: Deploy mongodb
          ansible.builtin.include_role:
            name: wpnops.mongodb
          vars:
            _map_format: 'nephelaiio.plugins.map_format'
            _addr_attrs: ['ansible_default_ipv4', 'address']
            _addresses: "{{ play_hosts | map('extract', hostvars, _addr_attrs) }}"
            _members: "{{ _addresses | list }}"
            mongodb_replicaset_members: "{{ _members | map(_map_format, '%s:' + mongodb_port) | list }}"

      rescue:
        - name: Set result facts
          ansible.builtin.set_fact:
            _members_failed: true

      always:
        - name: Destroy virtualenv
          ansible.builtin.file:
            path: "{{ _virtualenv_tmpdir.path }}"
            state: absent
          changed_when: false

    - name: Fail on broken replicaset member configuration
      ansible.builtin.fail:
        msg: "broken replicaset member configuration operation must fail"
      when: not _members_failed
