---
name: molecule

on:

  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 5 * * 5"

defaults:

  run:
    working-directory: 'wpnops.mongodb'

jobs:

  lint:

    name: lint
    runs-on: ubuntu-latest
    steps:

      - name: check out the codebase
        uses: actions/checkout@v4
        with:
          path: 'wpnops.mongodb'

      - name: set up python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: install make
        run: sudo apt-get install -y make

      - name: install dependencies
        run: make install

      - name: lint code
        run: make lint

  molecule:

    name: molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - name: default
          - name: ufw
        image:
          - name: ubuntu2204
            command: /lib/systemd/systemd
            scenario: default
          - name: ubuntu2004
            command: /lib/systemd/systemd
            scenario: default
          - name: debian11
            command: /lib/systemd/systemd
            scenario: default
          - name: centos8
            command: /usr/lib/systemd/systemd
    steps:

      - name: check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'wpnops.mongodb'

      - name: set up python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: install make
        run: sudo apt-get install -y make

      - name: run molecule tests
        run: make test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DOCKER_IMAGE: ${{ matrix.image.name }}
          MOLECULE_COMMAND: ${{ matrix.image.command }}
          MOLECULE_SCENARIO: ${{ matrix.scenario.name }}
